linters:
  disable-all: true
  enable:
    # - gosec
    - bodyclose
    - deadcode
    - gosimple
    - govet
    - staticcheck
    - structcheck
    - unused
    - varcheck
    - whitespace

run:
  skip-dirs:
    - internal
    - temp
